### PR TITLE
Optimistic-load posts when editing post content

### PR DESCRIPTION
**Pull request by ndrewtl**

### CODE REVIEW

**Comment by zfaizal2** [comment]
when editing a topic, the topic disappears until transaction finalizes as seen below 
image

let's change this to maintain the topic content and update on finalization.

**Comment by ndrewtl** [comment]
> when editing a topic, the topic disappears until transaction finalizes as seen below image
> 
> let's change this to maintain the topic content and update on finalization.

Thanks for finding this-- I traced the problem and it's because of how the `LocalPost` type doesn't hold an address, so it's not possible to search for replies to it. I think I need to fiddle with the types a bit to get that to work, but it should be doable

**Comment by ndrewtl** [comment]
image
The topic-edit spinner, like the topic-create spinner is a bit poorly-aligned. @ana2201 , could you help me make it look a bit better when this PR is merged?

**Comment by ndrewtl** [comment]
> when editing a topic, the topic disappears until transaction finalizes as seen below image
> 
> let's change this to maintain the topic content and update on finalization.

I modified the way the front-end does state to accommodate editing vs. creating a post. @zfaizal2 could you take another look at this before I merge?

**Comment by zfaizal2** [comment]
I tried it a few times and I hit some error when editing a topic, not sure what happened...
image

**Comment by ndrewtl** [comment]
> I tried it a few times and I hit some error when editing a topic, not sure what happened... image

Was able to fix this, but it required some changes, if you have a moment, could you take another look before merge?

**Pull request merged**
