### PR TITLE
Add GIF Support

### PR DESCRIPTION
**Pull request by zfaizal2**
## Description
Add gif support for posts

### Screenshots
preview ---> https://forum-staging-qjgpse5hx-usedispatch.vercel.app/

Selection_218

Workspace 3_002

image

### CODE REVIEW

**Comment by ana2201** [comment]
@zfaizal2 I fixed the styles and tested the functionality a bit, please review it (I can't assign you as reviewer because this is your PR 😬 )

**Comment by zfaizal2** [comment]
image


mobile view should mirror what we have in figma, added link in channel

**Comment by ana2201** [comment]
> 

fixed

**Comment by ana2201** [comment]
> image
> 
> mobile view should mirror what we have in figma, added link in notion task

fixed

**Pull request merged**
